name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.2', '8.3' ]

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Symfony CLI
      run: |
        curl -sS https://get.symfony.com/cli/installer | bash
        mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install dev tools
      run: composer run-script tools install

    - name: Run test suite
      run: composer run-script tests
